let tasks: Array<any> = [
    {
        id: 1,
        address: "18 Henry st",
        city: "Golden Lion Garden",
        state: "Shatin",
        zip: "01742",
        price: "$500",
        title: "Cleaning Task",
        bedrooms: 4,
        bathrooms: 3,
        lat: 22.38833,
        long: 114.18333,
        picture: "https://s3-us-west-1.amazonaws.com/sfdc-demo/realty/house01.jpg",
        thumbnail: "https://s3-us-west-1.amazonaws.com/sfdc-demo/realty/house01sq.jpg",
        tags: "colonial",
        description: "Lorem ipsum dolor sit amet",
        requester: {
            id: 1,
            name: "Caroline Kingsley",
            title: "Busy Mom",
            picture: "https://s3-us-west-1.amazonaws.com/sfdc-demo/people/caroline_kingsley.jpg"
        }
    },
    {
        id: 2,
        address: "24 Pearl st",
        city: "Cambridge",
        state: "Kowloon City",
        zip: "02420",
        price: "$1,000",
        title: "Cooking Task",
        bedrooms: 5,
        bathrooms: 4,
        lat: 22.38325,
        long: 114.18825,
        picture: "https://s3-us-west-1.amazonaws.com/sfdc-demo/realty/house02.jpg",
        thumbnail: "https://s3-us-west-1.amazonaws.com/sfdc-demo/realty/house02sq.jpg",
        tags: "colonial",
        description: "Lorem ipsum dolor sit amet",
        requester: {
            id: 1,
            name: "Caroline Kingsley",
            title: "Busy Mom",
            picture: "https://s3-us-west-1.amazonaws.com/sfdc-demo/people/caroline_kingsley.jpg"
        }
    },
    {
        id: 3,
        address: "61 West Cedar st",
        city: "Boston",
        state: "MA",
        zip: "02420",
        price: "$2,000",
        title: "Private Tutor",
        bedrooms: 5,
        bathrooms: 4,
        lat: 22.38718,
        long: 114.18318,
        picture: "https://s3-us-west-1.amazonaws.com/sfdc-demo/realty/house03.jpg",
        thumbnail: "https://s3-us-west-1.amazonaws.com/sfdc-demo/realty/house03sq.jpg",
        tags: "contemporary",
        description: "Lorem ipsum dolor sit amet",
        requester: {
            id: 2,
            name: "Michael Jones",
            title: "Busy Papa",
            picture: "https://s3-us-west-1.amazonaws.com/sfdc-demo/people/michael_jones.jpg"
        }
    },
    {
        id: 4,
        address: "32 Prince st",
        city: "Cambridge",
        state: "MongKok",
        zip: "02420",
        price: "$300",
        title: "Baby sitter",
        bedrooms: 5,
        bathrooms: 4,
        lat: 22.37309,
        long: 114.1709,
        picture: "https://s3-us-west-1.amazonaws.com/sfdc-demo/realty/house04.jpg",
        thumbnail: "https://s3-us-west-1.amazonaws.com/sfdc-demo/realty/house04sq.jpg",
        tags: "victorian",
        description: "Lorem ipsum dolor sit amet",
        requester: {
            id: 3,
            name: "Jonathan Bradley",
            title: "Busy Papa",
            picture: "https://s3-us-west-1.amazonaws.com/sfdc-demo/people/jonathan_bradley.jpg"
        }
    },
    {
        id: 5,
        address: "211 Charles Street",
        city: "Boston",
        state: "MA",
        zip: "02420",
        price: "$850,000",
        title: "Cleaning Task",
        bedrooms: 3,
        bathrooms: 2,
        lat: 22.38223,
        long: 114.19223,
        picture: "https://s3-us-west-1.amazonaws.com/sfdc-demo/realty/house05.jpg",
        thumbnail: "https://s3-us-west-1.amazonaws.com/sfdc-demo/realty/house05sq.jpg",
        tags: "contemporary",
        description: "Lorem ipsum dolor sit amet",
        requester: {
            id: 4,
            name: "Jennifer Wu",
            title: "Busy Papa",
            picture: "https://s3-us-west-1.amazonaws.com/sfdc-demo/people/jennifer_wu.jpg"
        }
    },
    {
        id: 6,
        address: "448 Hanover st",
        city: "Boston",
        state: "MA",
        zip: "02420",
        price: "$725,000",
        title: "Cleaning Task",
        bedrooms: 4,
        bathrooms: 2,
        lat: 22.39424,
        long: 114.18424,
        picture: "https://s3-us-west-1.amazonaws.com/sfdc-demo/realty/house06.jpg",
        thumbnail: "https://s3-us-west-1.amazonaws.com/sfdc-demo/realty/house06sq.jpg",
        tags: "colonial",
        description: "Lorem ipsum dolor sit amet",
        requester: {
            id: 5,
            name: "Olivia Green",
            title: "Busy Papa",
            picture: "https://s3-us-west-1.amazonaws.com/sfdc-demo/people/olivia_green.jpg"
        }
    },
    {
        id: 7,
        address: "127 Endicott st",
        city: "Boston",
        state: "MA",
        zip: "02420",
        price: "$450,000",
        title: "Cleaning Task",
        bedrooms: 3,
        bathrooms: 1,
        lat: 22.37424,
        long: 114.16424,
        picture: "https://s3-us-west-1.amazonaws.com/sfdc-demo/realty/house07.jpg",
        thumbnail: "https://s3-us-west-1.amazonaws.com/sfdc-demo/realty/house07sq.jpg",
        tags: "colonial",
        description: "Lorem ipsum dolor sit amet",
        requester: {
            id: 6,
            name: "Miriam Aupont",
            title: "Busy Papa",
            picture: "https://s3-us-west-1.amazonaws.com/sfdc-demo/people/miriam_aupont.jpg"
        }
    },
    {
        id: 8,
        address: "48 Brattle st",
        city: "Cambridge",
        state: "MA",
        zip: "02420",
        price: "$450,000",
        title: "Cleaning Task",
        bedrooms: 5,
        bathrooms: 4,
        lat: 22.40424,
        long: 114.20424,
        picture: "https://s3-us-west-1.amazonaws.com/sfdc-demo/realty/house10.jpg",
        thumbnail: "https://s3-us-west-1.amazonaws.com/sfdc-demo/realty/house10sq.jpg",
        tags: "victorian",
        description: "Lorem ipsum dolor sit amet",
        requester: {
            id: 7,
            name: "Michelle Lambert",
            title: "Busy Papa",
            picture: "https://s3-us-west-1.amazonaws.com/sfdc-demo/people/michelle_lambert.jpg"
        }
    },
    {
        id: 9,
        address: "121 Harborwalk",
        city: "Boston",
        state: "MA",
        zip: "02420",
        price: "$450,000",
        title: "Cleaning Task",
        bedrooms: 3,
        bathrooms: 3,
        lat: 22.39424,
        long: 114.19424,
        picture: "https://s3-us-west-1.amazonaws.com/sfdc-demo/realty/house09.jpg",
        thumbnail: "https://s3-us-west-1.amazonaws.com/sfdc-demo/realty/house09sq.jpg",
        tags: "contemporary",
        description: "Lorem ipsum dolor sit amet",
        requester: {
            id: 2,
            name: "Michael Jones",
            title: "Busy Papa",
            picture: "https://s3-us-west-1.amazonaws.com/sfdc-demo/people/michael_jones.jpg"
        }
    },
    {
        id: 10,
        address: "503 Park Drive",
        city: "Boston",
        state: "MA",
        zip: "02420",
        price: "$650,000",
        title: "Cleaning Task",
        bedrooms: 2,
        bathrooms: 2,
        lat: 22.39424,
        long: 114.20424,
        picture: "https://s3-us-west-1.amazonaws.com/sfdc-demo/realty/house08.jpg",
        thumbnail: "https://s3-us-west-1.amazonaws.com/sfdc-demo/realty/house08sq.jpg",
        tags: "contemporary",
        description: "Lorem ipsum dolor sit amet",
        requester: {
            id: 1,
            name: "Caroline Kingsley",
            title: "Busy Papa",
            picture: "https://s3-us-west-1.amazonaws.com/sfdc-demo/people/caroline_kingsley.jpg"
        }
    },
    {
        id: 11,
        address: "95 Gloucester st",
        city: "Boston",
        state: "MA",
        zip: "02420",
        price: "$690,000",
        title: "Cleaning Task",
        bedrooms: 3,
        bathrooms: 3,
        lat: 22.38424,
        long: 114.19424,
        picture: "https://s3-us-west-1.amazonaws.com/sfdc-demo/realty/house11.jpg",
        thumbnail: "https://s3-us-west-1.amazonaws.com/sfdc-demo/realty/house11sq.jpg",
        tags: "contemporary",
        description: "Lorem ipsum dolor sit amet",
        requester: {
            id: 4,
            name: "Jennifer Wu",
            title: "Busy Papa",
            picture: "https://s3-us-west-1.amazonaws.com/sfdc-demo/people/jennifer_wu.jpg"
        }
    },
    {
        id: 12,
        address: "145 Commonwealth ave",
        city: "Boston",
        state: "MA",
        zip: "02420",
        price: "$845,000",
        title: "Cleaning Task",
        bedrooms: 4,
        bathrooms: 3,
        lat: 22.39424,
        long: 114.18424,
        picture: "https://s3-us-west-1.amazonaws.com/sfdc-demo/realty/house12.jpg",
        thumbnail: "https://s3-us-west-1.amazonaws.com/sfdc-demo/realty/house12sq.jpg",
        tags: "colonial",
        description: "Lorem ipsum dolor sit amet",
        requester: {
            id: 5,
            name: "Olivia Green",
            title: "Busy Papa",
            picture: "https://s3-us-west-1.amazonaws.com/sfdc-demo/people/olivia_green.jpg"
        }
    }
];

export default tasks;
